# Change these first
owner: zoobean # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Landing
    url: https://www.beanstack.com/
  - name: App
    url: https://zoobean.beanstack.org/reader365
  - name: Canada
    url: https://canada.beanstack.com/reader365
  - name: Books
    url: $BOOKS_URL
  - name: Data
    url: $DATA_URL
  - name: Ops
    check: "tcp-ping"
    url: $OPS_URL
    port: $OPS_PORT

assignees:
  - tle105
  - yknx4

user-agent: zoobean/1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://assets.beanstack-cdn.com/static-assets/images/Logo.svg
  name: Zoobean Status
  theme: Dark
  introTitle: "**Beanstack** by Zoobean."
  introMessage: The leading solution for motivating people to read, Beanstack uses competition, recognition, and proven gamification principles to grow community reading culture.
  navbar:
    - title: Status
      href: /
    - title: Beanstack
      href: https://www.beanstack.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
